### ISSUE TITLE
genericEmail error -  SendGrid Transactional Email 

### ISSUE THREAD

**Issue by zoltanhalasz** [fireship-io/fireship.io#146]
Unhandled error { Error: Bad Request
    at Request.http [as _callback] (node_modules/@sendgrid/client/src/classes/client.js:124:25)
    at Request.self.callback (node_modules/request/request.js:185:22)
    at emitTwo (events.js:126:13)
    at Request.emit (events.js:214:7)
    at Request.<anonymous> (node_modules/request/request.js:1161:10)
    at emitOne (events.js:116:13)
    at Request.emit (events.js:211:7)
    at IncomingMessage.<anonymous> (node_modules/request/request.js:1083:12)
    at Object.onceWrapper (events.js:313:30)
    at emitNone (events.js:111:20)
  code: 400,
  message: 'Bad Request',
  response: 
   { headers: 
      { server: 'nginx',
        date: 'Wed, 10 Jul 2019 08:37:24 GMT',
        'content-type': 'application/json',
        'content-length': '646',
        connection: 'close',
        'access-control-allow-origin': 'https://sendgrid.api-docs.io',
        'access-control-allow-methods': 'POST',
        'access-control-allow-headers': 'Authorization, Content-Type, On-behalf-of, x-sg-elas-acl',
        'access-control-max-age': '600',
        'x-no-cors-reason': 'https://sendgrid.com/docs/Classroom/Basics/API/cors.html' },
     body: { errors: [Array] } } }

**Comment by RRGT19** [comment]
I am experiencing the same issue with the newComment function, see photo attached.

**package.json**
```
"dependencies": {
    "@sendgrid/mail": "^6.4.0",
    "firebase-admin": "~7.0.0",
    "firebase-functions": "^2.3.1"
  },
  "devDependencies": {
    "@sendgrid/mail": "^6.4.0",
    "tslint": "^5.12.0",
    "typescript": "^3.2.2"
  },
```

![Screen Shot 2019-07-10 at 2 41 13 PM](https://user-images.githubusercontent.com/33521443/60995629-dfc4ac00-a320-11e9-9121-9ac89f451d46.png)

I hope someone can help us.

**Comment by zoltanhalasz** [comment]
Hi,

Please look to the error message in the body above. Do a try catch and within the catch, console log the body errors.

Az Android Outlook<https://aka.ms/ghei36> letöltése

________________________________
